name: Ensure Project Builds Successfully

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install project dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Check for uncommitted build changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Error: Build produced uncommitted changes. Please run 'npm run build' locally and commit the changes."
            git status
            git diff
            exit 1
          else
            echo "✅ No uncommitted changes detected after build"
          fi
